### ISSUE TITLE
.local/share/applications .desktop files

### ISSUE THREAD

**Issue by zoof** [trizen/Linux-DesktopFiles#1]
Would it be possible/reasonable to add ~/.local/share/applications to the search path?  I'm asking because locally installed .desktop files do not show up in obmenu-generator generated menu.xml files.

**Comment by trizen** [comment]
The search paths can be specified in the `config.pl` file of obmenu-generator, as:

```perl
desktop_files_paths => [
   "/usr/share/applications",
   "/usr/local/share/applications",
   "$ENV{HOME}/.local/share/applications",
   "$ENV{HOME}/Desktop",
],
```

...where `desktop_files_paths` is a sub-option for `Linux::DesktopFiles`.

Since the version 0.71 of `obmenu-generator`, the path `~/.local/share/applications` is included by default in the configuration file. (https://github.com/trizen/obmenu-generator/commit/ae2f0f32a1f774eccb61c627ba7af5a959609468)

However, if you use obmenu-generator prior to that version, you need to manually add the path in.

Please let me know if this fixes your issue. Thanks!

**Comment by zoof** [comment]
Wonderful!  Many thanks!
